### ISSUE TITLE
Try to use filter example results in error

### ISSUE THREAD

**Issue by rufreakde** [ledongthuc/goterators#19]
Hi,
I imported the lib and also did go mod tidy all good  but when I just try to filter anything:
```go
	list := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}

	filteredItems, err := goterators.Filter(list, func(item int) bool {
		return item % 2 == 0
	})
```
i get:
<img width="985" alt="Screenshot 2022-08-15 at 10 51 31" src="https://user-images.githubusercontent.com/28104368/184605684-c36147b2-9402-487c-a7e8-62e9e0bd4cc6.png">

I just copied the example. Is this a bug @ledongthuc?

**Comment by ledongthuc** [comment]
Hi @rufreakde, first of all, thanks for your report.
It's an issue of documentation, the code should be:
```
	list := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}

	filteredItems := goterators.Filter(list, func(item int) bool {
		return item % 2 == 0
	})
```

The filter function won't return an error. So could you try again without a return error?

I will appreciate it if you can help to update the README document to correct it, or I will update it later this weekend.

**Comment by rufreakde** [comment]
Seemed not to help:
<img width="1143" alt="Screenshot 2022-08-15 at 11 22 02" src="https://user-images.githubusercontent.com/28104368/184610565-d5cec9b5-210f-4bff-bc3c-ccfa23eb11cf.png">

My code looks like this:
```go
	list := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}

	filteredItems := goterators.Filter( list, func(item int) bool {
		return item % 2 == 0
	})
```

go version:
`go version go1.18.5 darwin/amd64`

this is how the definition looks like:
```
package goterators

// Filter return items that pass the filter function.
func Filter[T any](source []T, filteredFunc func(item T) bool) (output []T) {
	for _, item := range source {
		if filteredFunc(item) {
			output = append(output, item)
		}
	}
	return output
}
```

Dont know why it thinks the parameters are not correct?

**Comment by ledongthuc** [comment]
It works from my side, with go version 1.18. My code:

```go
package main

import (
        "fmt"

        "github.com/ledongthuc/goterators"
)

func main() {
        list := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}

        filteredItems := goterators.Filter(list, func(item int) bool {
                return item%2 == 0
        })
        fmt.Println("list: ", list)
        fmt.Println("filteredItems: ", filteredItems)
}
```

![Screenshot 2022-08-15 at 12 07 35](https://user-images.githubusercontent.com/1828895/184617080-bba2e299-e27f-4873-b6b3-09f3a9d4ddcf.png)

But I think something is wrong with your IDE that can be configured to a lower version.

**Comment by rufreakde** [comment]
Very strange indeed i tested it as well and go version 18 works it seems to be an issue appearing with the plugin
https://marketplace.visualstudio.com/items?itemName=golang.Go

It is the first time I experienced this kind of issue.

<img width="944" alt="Screenshot 2022-08-15 at 14 33 04" src="https://user-images.githubusercontent.com/28104368/184635684-3b4636bc-42e7-4458-8a5e-260c8001c50e.png">
.

**Comment by ledongthuc** [comment]
ok, I don't have much experience in the visual studio and its plugin. But let's try a few troubleshooting steps:
 - Close and reopen VisualStudio again, and test if it works
 - Uninstall and re-install the plugin, and test if it works
 - And finally, uninstall and reinstall the visual studio, and test if it works again.

Sorry because I'm using VIm.

**Comment by rufreakde** [comment]
Tried seems not to work. Would be nice to see if someone else using VSCODE is having a similar issue.
Could hinder a wider adoption of the lib. I will try to find a colleague to test it on their system.

**Comment by ledongthuc** [comment]
Ok, it will be good. I think the ticket is solved. But let's keep it open and I remember to update README.
Again, thanks for your report.
